
name: "Deploy"

description: "Deploy newest code to the machine."

inputs:
  folder-name:
    description: "Project folder name"
    required: true
  env-value:
    description: "env file value"
    required: false
  ssh-key:
    description: "Ssh key for login the target machine"
    required: true
  host-name:
    description: "Host domain or ip"
    required: true
  user-name:
    description: "user to ssh,ex root,devops.."
    required: true

runs:
  using: "composite"
  steps:
    - name: Pulling newest code and restart docker-compose
      uses: fifsky/ssh-action@master
      with:
        command: |
          mkdir -p ${{ inputs.folder-name }}
          scp docker-compose.yaml ${{ inputs.host-name }}@${{ inputs.user-name }}:${{ inputs.folder-name }}
          cd ${{ inputs.folder-name }}
          docker-compose down && docker-compose up -d
        host: ${{ inputs.host-name }}
        user: ${{ inputs.user-name }}
        key: ${{ inputs.ssh-key }}